/**
 * `hush export` — plaintext out, as a last resort (and the names the shell hook needs).
 */
import { restrictToOwner } from "../platform.ts";
import { existsSync, readFileSync, writeFileSync, appendFileSync, chmodSync, lstatSync } from "node:fs";
import { join } from "node:path";
import { audit } from "../vault.ts";
import { requireIdentity } from "../identity.ts";
import { toEnvFile, toShellExports } from "../run.ts";
import { checkScopes } from "../policy.ts";
import { composeSets } from "../library.ts";
import { requestApproval } from "../approval.ts";
import { type Args, bool, str } from "../cli/args.ts";
import { ctxLoose, dieOnApproval, policyFor } from "../cli/context.ts";
import { collectExtraSets } from "../cli/sets.ts";
import { die, dim, info, out, warn } from "../cli/output.ts";

export async function cmdExport(a: Args): Promise<void> {
  const loose = ctxLoose(a);
  const id = requireIdentity();

  // Must match `hush run` exactly, library links included — materialising only
  // one set used to mean export silently omitted whatever else `hush run`
  // would have injected, so the shell hook and any generated .env disagreed
  // with what the app actually got at run time.
  const extra = collectExtraSets(a);
  const { secrets, layers, missing, blocked } = composeSets(loose.vault, id, loose.hushDir, extra);
  if (missing.length) warn(`Not exported: ${missing.join(", ")} — your library does not have them.`);
  for (const b of blocked) warn(`Not exported: ${b.name} — it is only for ${b.onlyIn.join(", ")}.`);

  // Used by the shell hook to know what to unset again on the way out. Reveals
  // no value, so this is never gated — the hook depends on it always working.
  if (bool(a, "names")) {
    for (const k of Object.keys(secrets).sort()) out(k);
    return;
  }

  // Everything past here writes values somewhere (stdout or --out), so it is
  // the "reveal" action regardless of format. checkEnv() is not needed: every
  // set in `layers` (including "default") is exactly what checkScopes() checks.
  const policy = policyFor(loose.hushDir);
  if (policy) {
    checkScopes(policy, layers);
    if (policy.requireApproval.includes("reveal")) {
      const ap = await requestApproval(loose.hushDir, {
        action: "reveal",
        summary: `Export ${Object.keys(secrets).length} secret(s)`,
        detail: [`Using sets:  ${layers.join(", ") || "(none)"}`],
        scope: `reveal:export:${layers.join("+")}`,
        ttlSeconds: policy.approvalTtlSeconds,
        timeoutMs: Math.max(1, policy.approvalTimeoutSeconds) * 1000,
        biometry: policy.biometry,
        // One-shot: a grant cannot outlive this command (approval.ts sessionGrant).
        sessionGrant: false,
      });
      dieOnApproval(ap, "export");
    }
  }

  const format = str(a, "format") || (bool(a, "shell") ? "shell" : "env");
  const outFile = str(a, "out");

  const source = loose.vault ? `vault "${loose.vault.data.name}"` : "your library";
  const body =
    format === "json"
      ? JSON.stringify(secrets, null, 2) + "\n"
      : format === "shell"
        ? toShellExports(secrets)
        : toEnvFile(secrets, `generated by hush from ${source} (${layers.join(", ") || "nothing"}) — do not commit`);

  audit(loose.hushDir, { actor: "cli", action: "export", layers, format, to: outFile ?? "stdout" });

  if (outFile) {
    // writeFileSync and chmodSync both follow a symlink at the destination, so
    // a link planted in the repo (git stores them, and .env is a plausible
    // target) would send the whole plaintext set to a file outside the project
    // and re-permission that file. Refuse anything that is not a regular file;
    // a regular file is still overwritten on purpose, which is the 0600
    // re-mode below. The same "never write through a symlink" refusal the
    // grants file used to need — it is gone, this one is not.
    const existingOut = lstatSync(outFile, { throwIfNoEntry: false });
    if (existingOut && !existingOut.isFile()) {
      die(
        `${outFile}: not a regular file — hush will not write plaintext through a ` +
          `symlink or special file placed at that path.`,
      );
    }
    writeFileSync(outFile, body, { mode: 0o600 });
    // writeFileSync only applies mode on creation; an existing file keeps its
    // old permissions, which for a stray .env is usually 0644.
    chmodSync(outFile, 0o600);
    restrictToOwner(outFile);
    const gi = join(process.cwd(), ".gitignore");
    const entry = outFile.replace(/^\.\//, "");
    const current = existsSync(gi) ? readFileSync(gi, "utf8") : "";
    if (!current.split(/\r?\n/).includes(entry)) {
      appendFileSync(gi, (current.endsWith("\n") || !current ? "" : "\n") + entry + "\n");
      info(dim(`  added ${entry} to .gitignore`));
    }
    warn(`Wrote ${Object.keys(secrets).length} plaintext secret(s) to ${outFile} (mode 0600).`);
    // A .env is a format to be *parsed*. Its quoting is dotenv's, not a shell's,
    // and it cannot be both — so a value containing a command substitution is
    // inert to every dotenv loader and live to `source`. `--shell` exists for
    // the shell case and is quoted for it.
    info(dim(`  Parse it, don't source it: \`set -a; . ${outFile}\` would let a value run.`));
    info(dim(`  For a shell, use: eval "$(hush export --shell)"`));
    info(dim("  Better still, `hush run -- <cmd>` keeps them off disk entirely."));
  } else {
    process.stdout.write(body);
  }
}
